# Start FROM ubuntu image
FROM ubuntu:20.04

# Install linux packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt update
RUN apt install --no-install-recommends -y gcc git zip curl htop libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg build-essential

# Get EdgeLab
RUN git clone https://github.com/Seeed-Studio/EdgeLab -b main --depth 1

# Install pip packages
RUN python3 -m pip install --upgrade pip wheel
RUN cd EdgeLab && pip install --no-cache -r requirements/pytorch_cpu.txt
RUN cd EdgeLab && pip install --no-cache -r requirements/base.txt
RUN cd EdgeLab && pip install --no-cache -r requirements/export.txt
RUN cd EdgeLab && pip install --no-cache -r requirements/inference.txt
RUN cd EdgeLab && mim install --no-cache -r requirements/mmlab.txt

WORKDIR /workspace

# Set environment variables
ENV OMP_NUM_THREADS=1

# Cleanup
RUN rm -rf EdgeLab
ENV DEBIAN_FRONTEND teletype